# Información del Sitio
title: Jiyū Uzumaki
subtitle: Datos del Personaje OC para Rol Escrito
email: tu-email@ejemplo.com
description: Repositorio dedicado a Jiyū Uzumaki, un Genin del Clan Uzumaki con habilidades sensoriales excepcionales y maestría en Fuinjutsu.
baseurl: "/jiyu" # el nombre de tu repositorio
url: "https://hmarort.github.io" # tu URL de GitHub Pages

# Información Personal/Autor
author: hmarort
street_address: 
city: El Puerto de Santa María
state: Andalucía
zip_code: 
country: España
phone: 

socials:
  GitHub: https://github.com/hmarort
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/hmarort
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
